const languages = [
  { code: 'af', name: 'Afrikaans' },                   // Afrikaans
  { code: 'sq', name: 'Albanês' },                     // Albanian
  { code: 'am', name: 'Amárico' },                     // Amharic
  { code: 'ar', name: 'Árabe' },                       // Arabic
  { code: 'hy', name: 'Armênio' },                     // Armenian
  { code: 'az', name: 'Azerbaijano' },                 // Azerbaijani
  { code: 'eu', name: 'Basco' },                       // Basque
  { code: 'be', name: 'Bielorusso' },                  // Belarusian
  { code: 'bn', name: 'Bengali' },                     // Bengali
  { code: 'bs', name: 'Bósnio' },                      // Bosnian
  { code: 'bg', name: 'Búlgaro' },                     // Bulgarian
  { code: 'ca', name: 'Catalão' },                     // Catalan
  { code: 'ceb', name: 'Cebuano' },                    // Cebuano
  { code: 'ny', name: 'Chichewa' },                    // Chichewa
  { code: 'zh-CN', name: 'Chinês (Simpplificado)' },   // Chinese (Simplified)
  { code: 'zh-TW', name: 'Chinês (Tradicional)' },     // Chinese (Traditional)
  { code: 'co', name: 'Córsega' },                     // Corsican
  { code: 'hr', name: 'Croata' },                      // Croatian
  { code: 'cs', name: 'Tcheco' },                      // Czech
  { code: 'da', name: 'Dinamarquês' },                 // Danish
  { code: 'nl', name: 'Holandês' },                    // Dutch
  { code: 'en', name: 'Inglês' },                      // English
  { code: 'eo', name: 'Esperanto' },                   // Esperanto
  { code: 'et', name: 'Estoniano' },                   // Estonian
  { code: 'tl', name: 'Filipino' },                    // Filipino
  { code: 'fi', name: 'Finlandês' },                   // Finnish
  { code: 'fr', name: 'Francês' },                     // French
  { code: 'fy', name: 'Frísio' },                      // Frisian
  { code: 'gl', name: 'Galego' },                      // Galician
  { code: 'ka', name: 'Georgiano' },                   // Georgian
  { code: 'de', name: 'Alemão' },                      // German
  { code: 'el', name: 'Grego' },                       // Greek
  { code: 'gu', name: 'Guzerate' },                    // Gujarati
  { code: 'ht', name: 'Crioulo Haitiano' },            // Haitian Creole
  { code: 'ha', name: 'Hauçá' },                       // Hausa
  { code: 'haw', name: 'Havaiano' },                   // Hawaiian
  { code: 'iw', name: 'Hebraico' },                    // Hebrew
  { code: 'hi', name: 'Hindi' },                       // Hindi
  { code: 'hmn', name: 'Hmong' },                      // Hmong
  { code: 'hu', name: 'Húngaro' },                     // Hungarian
  { code: 'is', name: 'Islandês' },                    // Icelandic
  { code: 'ig', name: 'Ibo' },                         // Igbo
  { code: 'id', name: 'Indonésio' },                   // Indonesian
  { code: 'ga', name: 'Irlandês' },                    // Irish
  { code: 'it', name: 'Italiano' },                    // Italian
  { code: 'ja', name: 'Japonês' },                     // Japanese
  { code: 'jw', name: 'Javanês' },                     // Javanese
  { code: 'kn', name: 'Kannada' },                     // Kannada
  { code: 'kk', name: 'Cazaque' },                     // Kazakh
  { code: 'km', name: 'Khmer' },                       // Khmer
  { code: 'ko', name: 'Coreano' },                     // Korean
  { code: 'ku', name: 'Curdo (Kurmanji)' },            // Kurdish (Kurmanji)
  { code: 'ky', name: 'Quirguiz' },                    // Kyrgyz
  { code: 'lo', name: 'Laosiano' },                    // Lao
  { code: 'la', name: 'Latim' },                       // Latin
  { code: 'lv', name: 'Letão' },                       // Latvian
  { code: 'lt', name: 'Lituano' },                     // Lithuanian
  { code: 'lb', name: 'Luxemburguês' },                // Luxembourgish
  { code: 'mk', name: 'Macedônio' },                   // Macedonian
  { code: 'mg', name: 'Malgaxe' },                     // Malagasy
  { code: 'ms', name: 'Malaio' },                      // Malay
  { code: 'ml', name: 'Malayalam' },                   // Malayalam
  { code: 'mt', name: 'Maltês' },                      // Maltese
  { code: 'mi', name: 'Maori' },                       // Maori
  { code: 'mr', name: 'Marathi' },                     // Marathi
  { code: 'mn', name: 'Mongol' },                      // Mongolian
  { code: 'my', name: 'Mianmarense (Birmanês)' },      // Myanmar (Burmese)
  { code: 'ne', name: 'Nepalês' },                     // Nepali
  { code: 'no', name: 'Norueguês' },                   // Norwegian
  { code: 'ps', name: 'Pastó' },                       // Pashto
  { code: 'fa', name: 'Persa' },                       // Persian
  { code: 'pl', name: 'Polonês' },                     // Polish
  { code: 'pt', name: 'Português' },                   // Portuguese
  { code: 'pa', name: 'Panjabi' },                     // Punjabi
  { code: 'ro', name: 'Romeno' },                      // Romanian
  { code: 'ru', name: 'Russo' },                       // Russian
  { code: 'sm', name: 'Samoano' },                     // Samoan
  { code: 'gd', name: 'Gaélico Escocês' },             // Scots Gaelic
  { code: 'sr', name: 'Sérvio' },                      // Serbian
  { code: 'st', name: 'Sesotho' },                     // Sesotho
  { code: 'sn', name: 'Shona' },                       // Shona
  { code: 'sd', name: 'Sindi' },                       // Sindhi
  { code: 'si', name: 'Cingalês' },                    // Sinhala
  { code: 'sk', name: 'Eslovaco' },                    // Slovak
  { code: 'sl', name: 'Esloveno' },                    // Slovenian
  { code: 'so', name: 'Somali' },                      // Somali
  { code: 'es', name: 'Espanhol' },                    // Spanish
  { code: 'su', name: 'Sundanês' },                    // Sundanese
  { code: 'sw', name: 'Suaíli' },                      // Swahili
  { code: 'sv', name: 'Sueco' },                       // Swedish
  { code: 'tg', name: 'Tajique' },                     // Tajik
  { code: 'ta', name: 'Tâmil' },                       // Tamil
  { code: 'te', name: 'Telugu' },                      // Telugu
  { code: 'th', name: 'Tailandês' },                   // Thai
  { code: 'tr', name: 'Turco' },                       // Turkish
  { code: 'uk', name: 'Ucraniano' },                   // Ukrainian
  { code: 'ur', name: 'Urdu' },                        // Urdu
  { code: 'uz', name: 'Uzbeque' },                     // Uzbek
  { code: 'vi', name: 'Vietnamita' },                  // Vietnamese
  { code: 'cy', name: 'Galês' },                       // Welsh
  { code: 'xh', name: 'Xhosa' },                       // Xhosa
  { code: 'yi', name: 'Yiddish' },                     // Yiddish
  { code: 'yo', name: 'Yorubá' },                      // Yoruba
  { code: 'zu', name: 'Zulu' }                         // Zulu
];
